### ISSUE TITLE
Only shows 1 channel in the spectogram in v0.9.1

### ISSUE THREAD

**Issue by Barough** [MikeWang000000/spek-X#13]
Looks like only 1 channel is shown in the Spectogram on 0.9.1 (Win 10/11)

![Bilderman 2023 01 25 18-21-34](https://user-images.githubusercontent.com/13651586/214636429-ad388e83-a73b-4af0-9d82-e624db3b7d62.png)

In v0.9.0 it said 2 channels

**Comment by MikeWang000000** [comment]
`channel 1 / 2` means this file have 2 channels and it is showing the spectrum of the 1st channel.
*Spek* supports switching channels by pressing `C` key, while *Spek-X*, based on old codebase, currently do not have this feature.
I'm going to add this in 0.9.2

**Comment by Barough** [comment]
Ok, thnx for the info.

But Spek-X 0.9.0 always showed 2 channels in the UI when u open a file in it.

Anyway... looking forward to 0.9.2 then ;)

**Comment by MikeWang000000** [comment]
Actually it's my mistake(>﹏<)  I leave this function half done.
Give me a few days...
In 0.9.2 you will able to see both `channel 1 / 2` and `channel 2 / 2`  :-P

**Comment by Barough** [comment]
Take your time ;-)

**Comment by MikeWang000000** [comment]
[Spek-X v0.9.2](https://github.com/MikeWang000000/spek-X/releases/tag/v0.9.2) released.
Press `C` to switch channels (￣∇￣)
