### ISSUE TITLE
[REQ] Monkey's Audio support

### ISSUE THREAD

**Issue by Barough** [MikeWang000000/spek-X#26]
Hi Mike
Would it be possible for you to add support for Monkey's Audio?

**Comment by MikeWang000000** [comment]
Hi, but I think Monkey's Audio (.ape) is already supported.

https://github.com/MikeWang000000/spek-X/blob/362dd16fb39e83cf95c5ab1af2d63135e1ad220a/tests/test-audio.cc#L74-L77

**Comment by Barough** [comment]
I get really wierd results here when checking APE files. I'll re-grab the latest Spek-X release and check again in a little while.

**Comment by Barough** [comment]
Looks like i was using an old version of spek-X. Everything look ok now.
