### ISSUE TITLE
Icon error when opening Spek

### ISSUE THREAD

**Issue by glu8716** [MikeWang000000/spek-X#3]
The program works fine but whenever I open it I get this error about invalid icons for two times.

![screen-2022-07-15-14-54-08](https://user-images.githubusercontent.com/33501455/179227637-0529deb1-0229-464f-8d3e-215ff064815b.png)

**Comment by MikeWang000000** [comment]
Have you tried `sudo make install`?

It looks like some people have this problem. #1, alexkay/spek#76
I can't reproduce it right now. Are the icons of Open, Save and Help displayed normally?

**Comment by glu8716** [comment]
Yes, all of those icons are displayed correctly.
Installing it seems to solve the problem, even if I'd preferred to keep it locally. Thanks!
