### ISSUE TITLE
m4a wont display spectrum, 0.9.0, x64

### ISSUE THREAD

**Issue by fcore117** [MikeWang000000/spek-X#4]
Test file here:
[Crysis 2 - Nano Catalyst.zip](https://github.com/MikeWang000000/spek-X/files/9143908/Crysis.2.-.Nano.Catalyst.zip)

![image](https://user-images.githubusercontent.com/1313813/179827295-8e206a82-903e-451e-9d09-720eef8bdf8f.png)

Win 10 x64

**Comment by Jocker666z** [comment]
same with monkey audio

**Comment by d4k0** [comment]
Same problem here. M4A worked in Spek-alternative.

**Comment by XPRAMT** [comment]
OGG格式也無法解析譜頻

**Comment by MikeWang000000** [comment]
Fixed by #11 
New release will come out in a few days.

**Comment by MikeWang000000** [comment]
[Spek-X v0.9.1](https://github.com/MikeWang000000/spek-X/releases/tag/v0.9.1) released.

**Comment by fcore117** [comment]
Rapid testing shows it works, i fed .flv .wmv .avi .mpeg .opus .mp3 .m4a .flac, 24bit and 16bit.... seems working
