### ISSUE TITLE
Support multiple audio streams

### ISSUE THREAD

**Issue by Erick2317** [MikeWang000000/spek-X#5]
As an **enhancement** or **new feature**, **files** with **multiple audio streams** in a **MKV**, **MP4** or **M2TS** container, only the **first audio stream** of the **file** is **recognized** while the other **streams** are **ignored** by the program. Here are some examples:
![2022-08-02](https://user-images.githubusercontent.com/91224267/182531505-c231fdbb-3e09-4c7d-9274-f8d374daddf8.png)
![00006 m2ts (1)](https://user-images.githubusercontent.com/91224267/182531521-96d2827f-af80-43de-8cdb-8df2b9016e19.png)
![2022-08-02 (1)](https://user-images.githubusercontent.com/91224267/182531536-ed2ccf6e-2580-40cb-b1f8-3ed10221ee8f.png)
![youtube-dl test video ''_ä↭𝕐  BaW_jenozKc mkv (1)](https://user-images.githubusercontent.com/91224267/182531552-7b66b0b6-ccf4-4e7c-a057-ba9474bcbc9a.png)

**Comment by MikeWang000000** [comment]
Hello, you can press `S` key or `Shift + S` to toggle between audio streams.  
Please refer to <https://github.com/MikeWang000000/spek-X/blob/main/MANUAL.md>. Thanks!

**Comment by Erick2317** [comment]
Now I can see the other audio streams. I will check the `MANUAL.md` to see the other keyboard shortcuts. Thanks for the help!
![00006 m2ts (2)](https://user-images.githubusercontent.com/91224267/183329765-8dd00acd-244d-4207-952b-eb7f50caa9ed.png)
![youtube-dl test video ''_ä↭𝕐  BaW_jenozKc mkv (2)](https://user-images.githubusercontent.com/91224267/183329777-d6c3e1f7-d9ad-4aa0-bde3-f579bf371849.png)
